// Generated by capnweb/examples:write-basic-example-file
import * as capnweb from "capnweb";

export async function runBasicDemo(connectUrl) {
  const session = await capnweb.newWebSocketRpcSession(connectUrl);
  const main = session.getRemoteMain();
  const pong = await main.ping();
  const stats = session.getStats();
  console.log("capnweb stats", stats);
  await session.drain();
  return pong;
}
